DROP TABLE IF EXISTS player_activity;
DROP TABLE IF EXISTS gc_predictions;
DROP TABLE IF EXISTS temp;
DROP TABLE IF EXISTS gc_data;
DROP TABLE IF EXISTS guilds;
DROP TRIGGER IF EXISTS player_data_ins ON extra_player_data;
DROP TRIGGER IF EXISTS player_data_upd ON extra_player_data;
DROP FUNCTION IF EXISTS update_player_activity CASCADE;
DROP VIEW IF EXISTS gc_matchups_id;
DROP VIEW IF EXISTS gc_matchups;
DROP VIEW IF EXISTS login_activity;
DROP TABLE IF EXISTS extra_player_data;
DROP TABLE IF EXISTS base_player_data;
DROP TABLE IF EXISTS timeslots;
DROP TABLE IF EXISTS gc_finals;
DROP TABLE IF EXISTS gc_events;
DROP TABLE IF EXISTS guild_ranks;
DROP TABLE IF EXISTS gc_days;
DROP TABLE IF EXISTS gc_prelims;
DROP TABLE IF EXISTS guild_ranks;
DROP TABLE IF EXISTS gc_groups;